### PR TITLE
Update AppDelegate+notification.m

### PR DESCRIPTION
**Pull request by fidoboy**
use mutableCopy on userInfo to get all custom properties and also aps

### CODE REVIEW

**Comment by fidoboy** [comment]
See here: https://github.com/AppGyver/PushNotifications/issues/3

**Comment by harsaharsa** [comment]
Thanks for this! We don't want to introduce breaking changes to the JS API at this point, so if you can refactor the pull request to put the custom payload contents inside `notification.custom.*` (as propsed in #3), we'd be happy to merge this after testing!

**Comment by fidoboy** [comment]
Yep, i'm sorry I just commented that out to make a fast test and try it on my build. It works fine, so I'll try to improve it to refactor the notification structure and keep current code working

**Comment by roberto-robles** [comment]
+1 That would solve #12

**Comment by josevillalobos** [comment]
+1 Working great :-)

**Comment by harsaharsa** [comment]
This pull request is way too broad at the moment, and contains several non-mergable/conflicting changes. Please open more atomic pull requests for different issues (Android fixes should be done against the next branch at the moment)!

**Comment by fidoboy** [comment]
LOL I'm sorry but don't understand how this github pull requests system works. It seems that all my other changes and test is being reflected here, I'm not sure why. I just wanted to suggest some little changes in my first commit

**Pull request closed without merging**
