### PR TITLE
Add custom attribute to notification object.

### PR DESCRIPTION
**Pull request by roberto-robles**

### CODE REVIEW

**Comment by roberto-robles** [comment]
For #12

**Comment by roberto-robles** [comment]
And based on #6 by @fidoboy

**Comment by fidoboy** [comment]
Great enhancement @roberto-robles ! cool! :smile:

**Comment by fidoboy** [comment]
You should add ```[payload removeObjectForKey: @"aps"];``` after creating the mutable copy. This way the maps object is not being duplicated. See my code here: https://github.com/fidoboy/PushNotifications/blob/master/src/ios/AppDelegate%2Bnotification.m I think that it's better this way

**Comment by harsaharsa** [comment]
We're tackling improvements to the iOS Push Plugin this week, I'll take these into account!

**Comment by harsaharsa** [comment]
This is now available in v1.1.2, pushed to master – the custom payload content is available under the `custom` key (with the `aps` content removed like @fidoboy suggested). Closing this!

**Pull request closed without merging**
